spring:
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}?currentSchema=${db.schema}
    username: ${db.user}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver

rest-client:
  base-url: ${base.url}